### ISSUE TITLE
J2000.0 coordinates from http://exoplanet.eu/catalog/

### ISSUE THREAD

**Issue by honamnguyen** [anjavdl/PHY517_AST443#1]
The RA and Dec coordinates of the host stars obtained from the catalog were recorded for the epoch J2000.0, which is at noon of January 1, 2000. We're observing the stars 16 years after this epoch so there must be some deviation in the coordinates. Is this difference negligible, and does it depend on the position of the chosen star?

"_Right ascension for "fixed stars" near the ecliptic and equator increases by about 3.3 seconds per year on average, or 5.5 minutes per century, but for fixed stars further from the ecliptic the rate of change can be anything from negative infinity to positive infinity. The right ascension of Polaris is increasing quickly. The North Ecliptic Pole in Draco and the South Ecliptic Pole in Dorado are always at right ascension 18h and 6h respectively._" from https://en.wikipedia.org/wiki/Right_ascension

**Comment by anjavdl** [comment]
The difference is negligible, our field-of-view is much bigger than a few arcseconds.

Moreover, a systematic shift in RA does not matter in practice:  we are aligning the telescope on stars, so if all of them shift by 3 minutes (i.e. 3 arcminutes x cosine(dec) ), we won't even notice.

The remaining changes in position relative to the "fixed sky" due to the proper motion of stars is very small for almost all objects.
